### ISSUE TITLE
有关推荐算法spark.py运行结果的问题

### ISSUE THREAD

**Issue by rosemary0x3f** [HuQi2018/BiSheServer#10]
作者大大你好，关于推荐算法的运行我有几个问题想请教一下，`linux`环境是完全按照`hadoop.sh`配置的，之后将`spark/jars`文件夹中的`mysql-connector-java-8.0.24.jar`文件复制到`linux`的`spark`的`jars`目录下，之后在`linux`下直接执行了`spark.py`程序，在执行之后报了几个警告。如下：
```
22/11/29 09:44:03 WARN util.Utils: Your hostname, VM-8-13-centos resolves to a loopback address: 127.0.0.1; using 10.0.8.13 instead (on interface eth0)
22/11/29 09:44:03 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
```
但`spark.py`还是执行完成了，且会将推荐结果写进`user_usermovierecommend`表中，但不论执行几次推荐算法，表中都只有一个用户有推荐结果，其它用户的推荐结果为空，还有一些用户没有加进到推荐表中，如下图所示：
![image](https://user-images.githubusercontent.com/117662261/204422547-0ca138e2-f6ba-4aaf-857b-0bf493f81ebe.png)
希望作者能指点一下，谢谢。

**Comment by HuQi2018** [comment]
1、WARN属于警告，可能是配置上的一些问题，只要是不影响程序运行也可以忽略。
2、始终只有一个用户有推荐结果，是因为在你的系统中其他用户没有操作记录，可能你这里只有用户ID为4的用户有操作记录，所以你可以尝试在其他几个用户上也做一些操作。（操作记录是指用户在对电影的浏览、收藏、评分、评论、搜索等功能的操作时，系统同时会对用户打标签的操作）

**Comment by TJzzzzz** [comment]
请问运行spark.py文件时一直显示拒绝连接是为什么呢
![Uploading 图片.png…]()

**Comment by TJzzzzz** [comment]
![@8IT)C56IGDCF~)E@R YFT4](https://user-images.githubusercontent.com/101857260/222939118-5fdc296c-d335-498c-a8ac-9f1b183ab85f.png)
作者你好，请问按照如上方法在linux中运行spark.py文件，一直显示拒绝连接是为什么呢

**Comment by HuQi2018** [comment]
请先确认服务是否正常开启&nbsp; 7077端口是否正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月5日(周日) 上午10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] 有关推荐算法spark.py运行结果的问题 (Issue #10)




 

 作者你好，请问按照如上方法在linux中运行spark.py文件，一直显示拒绝连接是为什么呢

**Comment by TJzzzzz** [comment]
作者你好，请问在执行spark.py之前还有什么必要操作吗，一直拒绝连接

**Comment by HuQi2018** [comment]
确认下spark能不能访问，端口 服务是否运行正常。实在不行 就在spark环境上运行spark.py文件(需要安装python)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月1日(周六) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] 有关推荐算法spark.py运行结果的问题 (Issue #10)




 
作者你好，请问在执行spark.py之前还有什么必要操作吗，一直拒绝连接
