### ISSUE TITLE
你好，请问这个地方是没有做分页处理吗

### ISSUE THREAD

**Issue by yellow-323** [HuQi2018/BiSheServer#14]
在首页这些点进去没有信息，上方标签栏都是正常的，首页也是最新电影那里进去跳转下页没有获取数据，这个地方是本来就没有做分页处理吗
![image](https://user-images.githubusercontent.com/125538701/229808110-2ef57d8b-f6a5-4076-8296-597c8d449aab.png)
![image](https://user-images.githubusercontent.com/125538701/229808422-06db8459-23e2-4b9c-9cba-da2b47e9b839.png)

**Comment by HuQi2018** [comment]
你的电影基础数据导入的是否有问题&nbsp; 把配置中的debug模式开下&nbsp; 看是否报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月4日(周二) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HuQi2018/BiSheServer] 你好，请问这个地方是没有做分页处理吗 (Issue #14)




 
在首页这些点进去没有信息，上方标签栏都是正常的，首页也是最新电影那里进去跳转下页没有获取数据，这个地方是本来就没有做分页处理吗
