### ISSUE TITLE
运行起来随便点一个页面 都报500

### ISSUE THREAD

**Issue by lizhiyou88** [HuQi2018/BiSheServer#15]
![image](https://user-images.githubusercontent.com/39184961/232732689-1a365409-e860-4f66-916d-928431140b6a.png)
![image](https://user-images.githubusercontent.com/39184961/232732726-6267259c-82d4-4e26-9ef9-7b848f96b416.png)

还每3秒刷新一次

**Comment by HuQi2018** [comment]
请在配置中将debug模式开启，查看具体错误原因

**Comment by FreeCurly** [comment]
运行起来随便点一个页面 都报500，打开debug模式后，报错如下 ：
1146, "Table 'localhost.movie_moviebrows' doesn't exist"

**Comment by HuQi2018** [comment]
请参照readme中的 6.安装配置说明 执行建表语句。
