### ISSUE TITLE
Hadoop初始化失败

### ISSUE THREAD

**Issue by RicardoEvan** [HuQi2018/BiSheServer#16]
![image](https://user-images.githubusercontent.com/78684733/232804046-d387e5f6-4ff5-4d6a-a9d0-8542fcd50155.png)
你好，我在虚拟机里安装Hadoop，结果最后初始化时出现这样子，可以帮忙看看吗

**Comment by HuQi2018** [comment]
抱歉，Hadoop涉及问题比较多、比较广，请自行使用搜索引擎解决。
