### ISSUE TITLE
部分表不存在

### ISSUE THREAD

**Issue by BZJiang** [HuQi2018/BiSheServer#17]
同学，你好！
刚开始学习这方面知识，你开源的项目给我了十分大的帮转，万分感谢。
想请问下，百度网盘里提供的表是不是不完全的，目前运行报错500。debug后显示表不存在。
![1681871432(1)](https://user-images.githubusercontent.com/126247886/232951302-7dfbebef-dd9e-40b2-9a65-4f7d89f07e6c.jpg)
同时想问下user_usersbase这张表是不是也没有呢？
![1681871495(1)](https://user-images.githubusercontent.com/126247886/232951464-4a99037f-5742-40b9-8ed0-12d24bfe3f8a.jpg)
谢谢！

**Comment by BZJiang** [comment]
这是我目前根据网盘提供的表导入的。
![1681871804(1)](https://user-images.githubusercontent.com/126247886/232952237-4e5010b8-470c-4a4e-b01f-a5bca9bd77ee.jpg)

**Comment by HuQi2018** [comment]
请参照readme中的 6.安装配置说明 执行建表语句。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 上午10:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HuQi2018/BiSheServer] 部分表不存在 (Issue #17)




 
同学，你好！
 刚开始学习这方面知识，你开源的项目给我了十分大的帮转，万分感谢。
 想请问下，百度网盘里提供的表是不是不完全的，目前运行报错500。debug后显示表不存在。
 
 同时想问下user_usersbase这张表是不是也没有呢？
 
 谢谢！
