### ISSUE TITLE
请问这是什么原因，是连不上数据库吗

### ISSUE THREAD

**Issue by hu133623** [HuQi2018/BiSheServer#19]
![image](https://user-images.githubusercontent.com/76836252/233562191-abd759d7-0a4e-453e-bbfe-398ccb979839.png)

**Comment by HuQi2018** [comment]
1、请首先排查mysql是否正常启动；
2、网络是否互通；
3、mysql数据库用户权限是否开放外网访问。

**Comment by hu133623** [comment]
感谢，已解决
