### ISSUE TITLE
bug: 导入movie_collectmoviedb SQL文件时报错

### ISSUE THREAD

**Issue by illusion77** [HuQi2018/BiSheServer#2]
如上。

**Comment by HuQi2018** [comment]
请给出具体错误信息

**Comment by illusion77** [comment]
<img width="1434" alt="WX20220221-193704@2x" src="https://user-images.githubusercontent.com/43769288/154948189-fd192995-56f0-4325-9e6c-a11a802be25f.png">
<img width="1440" alt="WX20220221-193836@2x" src="https://user-images.githubusercontent.com/43769288/154948203-750b755a-8fc0-413f-b7fe-5215f65e295b.png">

**Comment by illusion77** [comment]
可以加个联系方式调试吗。。可有偿

**Comment by TJzzzzz** [comment]
你好，请问这个怎么解决的呀

**Comment by HuQi2018** [comment]
请帖错误截图&nbsp; 导入之前请先运行创建表命令，导入时注意导入顺序



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] bug: 导入movie_collectmoviedb SQL文件时报错 (Issue #2)




 
你好，请问这个怎么解决的呀
