### ISSUE TITLE
邮箱验证问题

### ISSUE THREAD

**Issue by FreeCurly** [HuQi2018/BiSheServer#20]
你好，请问如果关闭了邮箱验证服务，那么注册时，验证码应该如何填写。还有一个问题就是，明明开启了邮箱验证服务，但是并未收到验证码，请问是什么原因。

**Comment by HuQi2018** [comment]
1、如果关闭验证码，验证码会通过下方提示返回。
2、请确认你的邮箱服务配置信息是否正确。

**Comment by FreeCurly** [comment]
> 1、如果关闭验证码，验证码会通过下方提示返回。 2、请确认你的邮箱服务配置信息是否正确。

请问具体应该如何修改邮箱服务配置信息，如果保留原有配置，是否会出现问题

**Comment by HuQi2018** [comment]
邮箱验证码属于资源型服务，默认配置是假的配置，需要自行更改成自己的资源。详情请百度 yagmail 配置qq邮箱 或 其他邮箱服务。
