### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by FreeCurly** [HuQi2018/BiSheServer#23]
![XJ6HJOXG7S 49MZ4J8(R_PO](https://user-images.githubusercontent.com/57836837/234166245-1e42eb11-4d70-4fe2-956f-42b9571daacf.png)
您好，请问这块内容具体应该如何配置

**Comment by HuQi2018** [comment]
请先搭好hadoop和spark集群后，再考虑此操作

**Comment by FreeCurly** [comment]
> 请先搭好hadoop和spark集群后，再考虑此操作

hadoop和spark集群均已搭建完毕，此处的内容应该如何配置，还望作者指点
