### ISSUE TITLE
图片链接失效

### ISSUE THREAD

**Issue by gitmarkchen** [HuQi2018/BiSheServer#27]
貌似之前爬取的电影图片链接已经失效
![image](https://github.com/HuQi2018/BiSheServer/assets/33871170/9849a216-a48e-4446-b169-609792a4b0ed)

**Comment by HuQi2018** [comment]
执行如下两条sql语句，同时清除redis缓存即可恢复链接，如个别图片还无法加载，请直接访问豆瓣搜索相关电影，手动更改相关图片地址。

UPDATE movie_collectmoviedb SET photos = REPLACE(photos, 'img3.doubanio.com', 'img1.doubanio.com') WHERE photos like "%img3.doubanio.com%";

UPDATE movie_collectmoviedb SET images = REPLACE(images, 'img3.doubanio.com', 'img1.doubanio.com') WHERE images like "%img3.doubanio.com%";
