### ISSUE TITLE
请问下软件版本不同会有影响吗

### ISSUE THREAD

**Issue by studyKQ** [HuQi2018/BiSheServer#31]
比如本机的hadoop3.1.3会有影响吗（还有就是有一套cdh集群可以套用进来吗）

**Comment by HuQi2018** [comment]
不同版本的hadoop需要使用对应版本的spark



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HuQi2018/BiSheServer] 请问下软件版本不同会有影响吗 (Issue #31)




 
比如本机的hadoop3.1.3会有影响吗（还有就是有一套cdh集群可以套用进来吗）

**Comment by studyKQ** [comment]
那么只要版本对应上就可以了吗？需要其他也改动吗？比如代码之类的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] 请问下软件版本不同会有影响吗 (Issue #31)




 不同版本的hadoop需要使用对应版本的spark <br&gt; <br&gt; <br&gt; <br&gt; ---原始邮件--- <br&gt; 发件人: ***@***.***&amp;amp;gt; <br&gt; 发送时间: 2024年11月7日(周四) 晚上9:03 <br&gt; 收件人: ***@***.***&amp;amp;gt;; <br&gt; 抄送: ***@***.***&amp;amp;gt;; <br&gt; 主题: [HuQi2018/BiSheServer] 请问下软件版本不同会有影响吗 (Issue #31) <br&gt; <br&gt; <br&gt; <br&gt; <br&gt;   <br&gt; 比如本机的hadoop3.1.3会有影响吗（还有就是有一套cdh集群可以套用进来吗） <br&gt;   <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;amp;gt;

**Comment by HuQi2018** [comment]
代码里应该是不用的，你可以跑一遍看看

**Comment by studyKQ** [comment]
好的，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] 请问下软件版本不同会有影响吗 (Issue #31)




 
代码里应该是不用的，你可以跑一遍看看
