### ISSUE TITLE
基础数据源失效问题

### ISSUE THREAD

**Issue by zhyoulove** [HuQi2018/BiSheServer#32]
![image](https://github.com/user-attachments/assets/846eecb8-7d08-4569-a1e3-9dd8872fb6a9)
ni'hao你好，这个网盘里面的sql文件可以在分享一下吗

**Comment by zhyoulove** [comment]
万分感谢

**Comment by Okakura-Tenshin** [comment]
所以有收集到吗

**Comment by HuQi2018** [comment]
看Readme中的链接。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月17日(周二) 晚上8:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [HuQi2018/BiSheServer] 基础数据源失效问题 (Issue #32)




 
所以有收集到吗
