### ISSUE TITLE
请问用的是什么推荐算法

### ISSUE THREAD

**Issue by Femalebully** [HuQi2018/BiSheServer#5]

**Comment by HuQi2018** [comment]
算法来源参考：[recommenderSystemBasedOnSpark](https://github.com/toughhou/recommenderSystemBasedOnSpark)

**Comment by TJzzzzz** [comment]
请问除了spark.py  其他地方用到的什么推荐算法呢

**Comment by HuQi2018** [comment]
其他地方并未使用什么算法，只是简单的类型相似匹配，和随机抽取。
