### ISSUE TITLE
基本数据可以在分享一下吗谢谢

### ISSUE THREAD

**Issue by hu133623** [HuQi2018/BiSheServer#7]
基本数据可以在分享一下吗谢谢

**Comment by wzg1058509446** [comment]
哪个项目？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuQi2018/BiSheServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 晚上10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HuQi2018/BiSheServer] 基本数据可以在分享一下吗谢谢 (Issue #7)





 
基本数据可以在分享一下吗谢谢

**Comment by hu133623** [comment]
就这个电影推荐系统啊

**Comment by wzg1058509446** [comment]
那个不是我的项目，你问问作者吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuQi2018/BiSheServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuQi2018/BiSheServer] 基本数据可以在分享一下吗谢谢 (Issue #7)





 
就这个电影推荐系统啊

**Comment by hu133623** [comment]
这就是他的项目的评论区吧，我刚就好奇你咋问我呢

**Comment by wzg1058509446** [comment]
噢不好意思，原来是我watch了这个项目，刚刚发来了邮件。

**Comment by hu133623** [comment]
没事的

**Comment by HuQi2018** [comment]
基础数据在Readme文件中有写哦，pdf里的过期了，而且不好改所以一直没动
下载基础数据：
    链接: https://pan.baidu.com/s/1XJTnuCVlDvbUG3zp4kk-Ag 提取码: ik32

**Comment by hu133623** [comment]
谢谢，还有微信公众号python联盟在卖你这个项目，100人民币

**Comment by HuQi2018** [comment]
唉，已经投诉过两三次了，投诉一次删一次
