### ISSUE TITLE
进入项目之后，跳转其他的页面就报500错误，前端无法获取data数据，是为啥呢？还有我没有找到user的相关表和数据，请问是在other.sql里面吗，谢谢您了

### ISSUE THREAD

**Issue by pmf200103** [HuQi2018/BiSheServer#8]
环境搭好，还有一些问题想请教

**Comment by HuQi2018** [comment]
在项目目录运行命令，创建表结构，同时创建Django管理系统的管理员帐号：
python manage.py makemigrations user movie api
python manage.py migrate
python manage.py createsuperuser
下载基础数据：
    链接: https://pan.baidu.com/s/1XJTnuCVlDvbUG3zp4kk-Ag 提取码: ik32
导入基础数据，导入顺序：movie_collectmoviedb.sql、movie_movietagdb.sql、other.sql

**Comment by pmf200103** [comment]
ok了，谢谢您
